export class PositionRecord{
    searchPositionID:string;

    positionID:string;
    prc:string;
    payClassification:string;
    positionDetails:string;

    autoGeneratedTimeGroup:string;
    autoGeneratedEmployeeGroup:string;
    kronosESSUser:string;
    mobileDeviceLicenseType:string;
    functionalAccessProfile:string;
    phase:string;
    assignKronosPattern:string;
    manuallyAssignedTimeGroup:string;
    manuallyAssignedEmployeeGroup:string;
    manuallyAssignedFunctionalAccessProfile:string;

    lastModifiedDate:string;
    lastModifiedUser:string;

}