/** 
test 
**/
export const PositionTableData: Array<any> = [
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'N',
        'mobileDeviceLicenseType': `B`,
        'functionalAccessProfile': 'A',
        'phase': 'AI',
        'assignKronosPattern': 'N',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'N',
        'mobileDeviceLicenseType': `B`,
        'functionalAccessProfile': 'A',
        'phase': 'AI',
        'assignKronosPattern': 'N',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',

        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '3017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '3004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'

    },
    {
        'autoGeneratedTimeGroup': '2017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '2004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'
    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'
    },
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'
    },    
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'
    },    
    {
        'autoGeneratedTimeGroup': '1017234SOPERSPLN',
        'autoGeneratedEmployeeGroup': '1004830SOPERNOPSSECU',
        'kronosESSUser': 'Y',
        'mobileDeviceLicenseType': `T`,
        'functionalAccessProfile': 'C',
        'phase': 'PY',
        'assignKronosPattern': 'Y',
        'manuallyAssignedTimeGroup': '3017234SOPERSPLN1',
        'manuallyAssignedEmployeeGroup': '3004830SOPERNOPSSECU1',
        'manuallyAssignedFunctionalAccessProfile': 'D',
        'lastModifiedDate': '03/04/2017 11:12:22',
        'lastModifiedUser': 'KCHUA'
    },            
];

